trigger:
  - develop
pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration: Release
steps:
  - checkout: self
    submodules: 'true'
  - task: UseDotNet@2
    displayName: Install .NET Core 5.0 SDK
    inputs:    
      packageType: sdk
      version: 5.0.x
      includePreviewVersions: true
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      packageType: sdk
      version: 3.1.x
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*tests/CampaignKit.WorldMap.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration)'
  - task: CopyFiles@2
    inputs:
      SourceFolder: >-
        $(System.DefaultWorkingDirectory)/src/CampaignKit.WorldMap.UI/bin/Release/net5.0
      Contents: publish.zip
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: drop
      publishLocation: Container
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: 'cl-test-001(7630a5f0-10f7-49a8-b19f-77f20ab880f6)'
      appType: 'functionAppLinux'
      appName: 'CampaignKitWorldMapFunction20210530183839'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'