// <auto-generated />
using System;
using CampaignKit.WorldMap.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampaignKit.WorldMap.Migrations
{
    [DbContext(typeof(MappingContext))]
    [Migration("20181205011411_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("CampaignKit.WorldMap.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdjustedSize");

                    b.Property<string>("ContentType");

                    b.Property<string>("Copyright");

                    b.Property<DateTime>("CreationTimestamp");

                    b.Property<string>("FileExtension");

                    b.Property<int>("MaxZoomLevel");

                    b.Property<string>("Name");

                    b.Property<bool>("RepeatMapInX");

                    b.Property<string>("Secret");

                    b.Property<string>("ThumbnailPath");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
