// <auto-generated />
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using System;
using CampaignKit.WorldMap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampaignKit.WorldMap.Migrations
{
    [DbContext(typeof(WorldMapDBContext))]
    [Migration("20201206144936_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("CampaignKit.WorldMap.Entities.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdjustedSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("FileExtension")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkerData")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxZoomLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RepeatMapInX")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShareKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTimestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorldFolderPath")
                        .HasColumnType("TEXT");

                    b.HasKey("MapId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("CampaignKit.WorldMap.Entities.Tile", b =>
                {
                    b.Property<int>("TileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletionTimestamp")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("DateTime");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoomLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("TileId");

                    b.HasIndex("MapId");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("CampaignKit.WorldMap.Entities.Tile", b =>
                {
                    b.HasOne("CampaignKit.WorldMap.Entities.Map", "Map")
                        .WithMany("Tiles")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
