// <copyright file="BlobCreatedEventData.cs" company="Jochen Linnemann - IT-Service">
// Copyright (c) 2017-2021 Jochen Linnemann, Cory Gill.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

namespace CampaignKit.WorldMap.Function
{
    /// <summary>
    /// Event data structure for blob creation events.
    /// see: https://docs.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage?tabs=event-grid-event-schema#microsoftstorageblobcreated-event .
    /// </summary>
    public class BlobCreatedEventData
    {
        /// <summary>
        /// Gets or sets the name of the API/operation that triggered this event.
        /// </summary>
        public string Api { get; set; }

        /// <summary>
        /// Gets or sets the request id provided by the client of the storage API operation that triggered this event.
        /// </summary>
        public string ClientRequestId { get; set; }

        /// <summary>
        /// Gets or sets the request id generated by the storage service for the storage API operation that triggered this event.
        /// </summary>
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or sets the path to the directory.
        /// </summary>
        public string Url { get; set; }

        /// <summary>
        /// Gets or sets the etag of the object at the time this event was triggered.
        /// </summary>
        public string ETag { get; set; }

        /// <summary>
        /// Gets or sets the content type of the blob. This is the same as what would be returned in the Content-Type header from the blob.
        /// </summary>
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or sets the size of the blob in bytes. This is the same as what would be returned in the Content-Length header from the blob.
        /// </summary>
        public int ContentLength { get; set; }

        /// <summary>
        /// Gets or sets the type of blob.
        /// </summary>
        public string BlobType { get; set; }

        /// <summary>
        /// Gets or sets the opaque string value representing the logical sequence of events for any particular directory name.
        /// Users can use standard string comparison to understand the relative sequence of two events on the same directory name.
        /// </summary>
        public string Sequencer { get; set; }
    }
}
